<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Both</name>
   <tag></tag>
   <elementGuidId>eedc69af-d843-4f0d-b457-f0204dee75ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='50965']/td[17]/div/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>70fad3b9-8e54-409b-b6c4-7c57ae4bb939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>2c45e373-9a0c-4289-aac3-2e5805e6cc94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>export dropdown-item</value>
      <webElementGuid>2e7b0580-45a7-4c84-b874-647d7421e845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-export-type</name>
      <type>Main</type>
      <value>ihsAndNormalized</value>
      <webElementGuid>291236cf-3848-42d5-86b5-16bc20185afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Both</value>
      <webElementGuid>3fb5f6d1-c15c-4f51-97b7-2a4f69812586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;50965&quot;)/td[@class=&quot;dt-body-center action-links&quot;]/div[@class=&quot;btn-group export-dropdown show&quot;]/ul[@class=&quot;dropdown-menu float-right project-export-bottom-margin show&quot;]/li[3]/a[@class=&quot;export dropdown-item&quot;]</value>
      <webElementGuid>6fd83a08-ef87-43fe-9fed-e3edc52c9bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4a4fd73d-f0c6-4f2c-8d4f-8e6d1a5077ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>f517721a-2c26-47bc-83bf-1ed78faf12aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>export dropdown-item</value>
      <webElementGuid>b9113675-bcac-4ff8-9b6c-ed9d1e8a3f30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-export-type</name>
      <type>Main</type>
      <value>ihsAndNormalized</value>
      <webElementGuid>f5f211d9-e95e-4902-b6d9-c29ee36dcce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Both</value>
      <webElementGuid>1c7eab98-0208-43b4-b4d1-c59a6901f92e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;50628&quot;)/td[@class=&quot;dt-body-center action-links&quot;]/div[@class=&quot;btn-group export-dropdown show&quot;]/ul[@class=&quot;dropdown-menu float-right project-export-bottom-margin show&quot;]/li[3]/a[@class=&quot;export dropdown-item&quot;]</value>
      <webElementGuid>760f21d7-8171-4edb-baf3-a6e09c7e50d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='50965']/td[17]/div/ul/li[3]/a</value>
      <webElementGuid>2c15fd35-16a5-4916-ba11-0821cf47eed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Both')]</value>
      <webElementGuid>fade626d-a01a-4127-89cb-7a62fd4f3131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='With Normalized FFF Attributes'])[1]/following::a[1]</value>
      <webElementGuid>6aaa3ad1-d563-4f86-a788-506d83bd98b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='With FFF Attributes'])[1]/following::a[2]</value>
      <webElementGuid>54e73667-b59f-41fd-bd89-f5fa678a9f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test'])[1]/preceding::a[3]</value>
      <webElementGuid>6410f7b1-a48c-46b1-97dd-9736f1c0f5cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GBS-ALT-50965'])[4]/preceding::a[3]</value>
      <webElementGuid>ef7447e6-414f-4e84-89d7-e7c8030bd1f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Both']/parent::*</value>
      <webElementGuid>25ea7cb4-3cd4-42d6-98c3-1e7b36b0111a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[7]</value>
      <webElementGuid>8f28730c-d4fa-458f-b5a0-e27dd61f7fe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[17]/div/ul/li[3]/a</value>
      <webElementGuid>8c1c67fa-c36e-4931-8d04-6526fdc567b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Both' or . = 'Both')]</value>
      <webElementGuid>8d7ce0f2-6cd0-4dd1-8af7-61383fb600b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='50628']/td[17]/div/ul/li[3]/a</value>
      <webElementGuid>f47638ad-6e11-42fa-b465-e7087e04b09b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test'])[3]/preceding::a[3]</value>
      <webElementGuid>e92ab9fe-2196-419f-bf3e-a65515db44ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GBS-ALT-50628'])[4]/preceding::a[3]</value>
      <webElementGuid>7656e07f-0c65-4a4a-a309-a229bc9abb8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
