<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Project success msg</name>
   <tag></tag>
   <elementGuidId>2b183d25-fbb0-43b1-bbfe-b254f4088798</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;stoast-panel&quot;)/div[@class=&quot;alert alert-success&quot;][count(. | //*[@class = 'alert alert-success' and (contains(text(), 'Project File for Dummy MPN successfully created') or contains(., 'Project File for Dummy MPN successfully created'))]) = count(//*[@class = 'alert alert-success' and (contains(text(), 'Project File for Dummy MPN successfully created') or contains(., 'Project File for Dummy MPN successfully created'))])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.alert.alert-success</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='stoast-panel']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>56053e94-7e27-4aff-99de-bacc2d6ce5f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert alert-success</value>
      <webElementGuid>e38eb85a-97c7-4aed-bce9-7374e9b64aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>b11139a0-dd40-40f3-8aaa-4e41d2c97f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Project File for Dummy MPN successfully created</value>
      <webElementGuid>3eb9d008-a9e8-4f4d-af7a-99e117164226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stoast-panel&quot;)/div[@class=&quot;alert alert-success&quot;]</value>
      <webElementGuid>da923eb5-f89a-4c15-9432-04dec4473887</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='stoast-panel']/div</value>
      <webElementGuid>6aa5864d-e9f5-492d-9fda-f0751035d18a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PIR / DIR'])[1]/preceding::div[3]</value>
      <webElementGuid>e9f1799d-5cc7-4eef-8dfe-92f13c18350b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Project GBS_AF_AC_MV_Sample File successfully created']/parent::*</value>
      <webElementGuid>a2240c20-7b69-4467-9a2d-a9d1bc53a46c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div</value>
      <webElementGuid>9a79ad27-415d-4c47-bccc-f4984d6aabf1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
