<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_return-arrow</name>
   <tag></tag>
   <elementGuidId>6f26e1da-cea9-46ef-85d9-b3fea3e64dbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-angle-left.dialog-return-arrow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='review-mpns-modal']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>6590949d-5152-47a9-828e-13e97760a3d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-angle-left dialog-return-arrow</value>
      <webElementGuid>38a24fea-6b92-4fcf-b902-54465ee4df08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f1be36cd-73aa-492b-aa0f-88fd5f7c8115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;review-mpns-modal&quot;)/i[@class=&quot;fa fa-angle-left dialog-return-arrow&quot;]</value>
      <webElementGuid>b40c8be4-0ed6-47f1-85df-6420d29494af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='review-mpns-modal']/i</value>
      <webElementGuid>24d4f188-325b-47c7-b35d-b0edff2e624a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/i</value>
      <webElementGuid>5d177920-1f07-454c-826c-af1436eff18d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
