<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dueDateRequest</name>
   <tag></tag>
   <elementGuidId>3a594270-cc2f-48c9-a939-60d861c7485b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#req-due-date-picker</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='req-due-date-picker']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6bc14ac9-f0b8-4ebb-ae99-7a1b1d2dbf67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>01c87a03-67a7-4ad8-b315-4e9f1e4c04e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b5dbe736-7b4e-4ed0-a229-ddc2293ea75f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dueDate</value>
      <webElementGuid>b0387d79-6422-451d-bce3-3153d795abf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>req-due-date-picker</value>
      <webElementGuid>dcff50d8-b714-45a9-a8ee-678a683d537a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;req-due-date-picker&quot;)</value>
      <webElementGuid>71770aae-ec4e-475c-9b41-93bc6c4be3f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='req-due-date-picker']</value>
      <webElementGuid>76f03c6e-c658-467f-a84b-a3e5ccef425d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='due-date-input']/input</value>
      <webElementGuid>6174387a-8ed8-4d5e-913b-d73060f0980a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>3526bf14-7a3e-41c1-a601-d3592c7452c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'dueDate' and @id = 'req-due-date-picker']</value>
      <webElementGuid>2c972f0e-49a3-468b-b1e5-1e769ad2833b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
