<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_RequestType</name>
   <tag></tag>
   <elementGuidId>056d5da5-d568-462c-a244-ba27d38f57ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sourcing-request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='sourcing-request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bac31f67-bf75-448f-a6a1-eec98f00efd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sourcingRequestType</value>
      <webElementGuid>1c006aec-f74e-414c-8996-ec128ad0485a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>03878392-04ac-4add-aaeb-7e8d73a9482b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sourcing-request</value>
      <webElementGuid>9191b2f1-0f83-419c-9ffa-fe0b8fa2bd5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>55fce497-d7bf-4215-85f0-759fe7592d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                
                                Advance Sourcing
                                GBS
                                PCN
                            </value>
      <webElementGuid>07aaa70f-d65f-4ade-bf99-115a366c4ba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sourcing-request&quot;)</value>
      <webElementGuid>69204b65-58b5-4e8d-9f4d-643c7ce872e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='sourcing-request']</value>
      <webElementGuid>a957617b-a3db-433d-abbd-152e267edc71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='req-project-form']/div[9]/div/select</value>
      <webElementGuid>c6506827-20fe-42b8-b4f1-06719c157af6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::select[1]</value>
      <webElementGuid>99728358-4c2a-4128-8e91-37e43e811621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/preceding::select[1]</value>
      <webElementGuid>7552f90c-fc19-43f5-9db6-6f3cfa837a94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/select</value>
      <webElementGuid>e56adb95-cfd3-498b-a746-75797e5e3e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'sourcingRequestType' and @id = 'sourcing-request' and (text() = '
                                
                                Advance Sourcing
                                GBS
                                PCN
                            ' or . = '
                                
                                Advance Sourcing
                                GBS
                                PCN
                            ')]</value>
      <webElementGuid>06dbaee7-03b0-4dd7-88ec-b2422b98da8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
