<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Organization</name>
   <tag></tag>
   <elementGuidId>415623c9-6a02-456e-ad88-07a1a08fe009</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#organization-filter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='organization-filter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>616cedd6-c380-4e59-a981-a8dc6080c417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectpicker form-control</value>
      <webElementGuid>c617386f-2ebd-42cc-badd-c0572c716565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>organization-filter</value>
      <webElementGuid>76b1e18b-2c9e-470c-80a8-b41a99fe5581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>organization</value>
      <webElementGuid>4451e072-56f0-46cf-be4c-00c1d45e7679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-style-base</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ee153221-6d18-49b0-8354-297606c04c87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Technical Sourcing
                Flex
            </value>
      <webElementGuid>bb78f2fe-9d07-44fd-8072-e97b7e1e7516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;organization-filter&quot;)</value>
      <webElementGuid>7c1d27c4-6063-4261-b0ea-0e684ba0a55c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='organization-filter']</value>
      <webElementGuid>7c7549a4-d2f0-4db2-b499-0eceb139826c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gbs-main-page']/div/div/div/div/select</value>
      <webElementGuid>f73c167e-12e4-4aad-b7a6-1c1f971da632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organization'])[1]/following::select[1]</value>
      <webElementGuid>7a07e724-71ce-455f-a682-bf283daee327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::select[1]</value>
      <webElementGuid>7ab2eed8-48fb-46de-b989-554dab7c34d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Technical Sourcing'])[2]/preceding::select[1]</value>
      <webElementGuid>a19c8248-2da7-422f-86f2-2c11a5e56b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Technical Sourcing'])[3]/preceding::select[1]</value>
      <webElementGuid>76c5f04e-b4d2-4e5f-997e-22365eb656a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>a60d90d1-d315-4331-9149-963519d813fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
