<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Application</name>
   <tag></tag>
   <elementGuidId>4a625751-cd96-4b75-861f-37a07d8e7c6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='application']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0bcef3b9-af52-4604-8240-3642e7681954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>application</value>
      <webElementGuid>f7b2cf80-577c-48fb-be71-3e44a1140e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>92abc80c-de81-4b33-807e-65501b8716e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application</value>
      <webElementGuid>8f04cbab-0048-4ba2-975a-0ebcc572cd13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8539b42c-fabe-4a40-912e-4da9e654a778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                
                                Automotive
                                Industrial
                                Medical
                                Military
                                Lifestyle
                                Others
                            </value>
      <webElementGuid>199a5c93-83d9-4e9b-b83a-002772c35330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application&quot;)</value>
      <webElementGuid>dabf7932-ee40-4487-b18f-9c09ddc06e43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='application']</value>
      <webElementGuid>c0618006-7ab3-4a01-92cd-0fe36e655237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='req-project-form']/div[10]/div/select</value>
      <webElementGuid>a61010c6-7946-47b7-9339-4228ba27b999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::select[1]</value>
      <webElementGuid>3cdca6d3-507b-402b-91f2-2b739f5729fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create'])[1]/preceding::select[1]</value>
      <webElementGuid>f32b4d49-1601-47a8-b7b1-4ee6d096dcef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::select[1]</value>
      <webElementGuid>cb424e6b-ef3e-4ba1-bec3-721fefa89fab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/select</value>
      <webElementGuid>bf93be44-18cc-4349-b863-7bc6fee9e797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'application' and @id = 'application' and (text() = '
                                
                                Automotive
                                Industrial
                                Medical
                                Military
                                Lifestyle
                                Others
                            ' or . = '
                                
                                Automotive
                                Industrial
                                Medical
                                Military
                                Lifestyle
                                Others
                            ')]</value>
      <webElementGuid>17303f3c-6d10-4b32-ae87-b19e0bd67e57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
