<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_012 - PCBA KALLANG, SINGAPORE (012)</name>
   <tag></tag>
   <elementGuidId>e80cd525-a728-4737-8684-d3d0e2156774</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bs-select-12-2 > span.text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bs-select-12-2']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>53401f05-8484-4ab2-924a-eeaa52f31386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>373f5576-5e5a-4aca-be4f-c0c11281fca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>012 - PCBA KALLANG, SINGAPORE (012)</value>
      <webElementGuid>e9ff988a-781e-4821-aed6-6adfc91f9793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-12-2&quot;)/span[@class=&quot;text&quot;]</value>
      <webElementGuid>9501f8dc-72f5-4f59-81db-17500298749a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0b0e794f-7f0b-4af0-9d44-c739e8ecf24f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>32521e88-b4ad-492c-b19f-371f022c81fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>012 - PCBA KALLANG, SINGAPORE (012)</value>
      <webElementGuid>a20733bc-ae48-45ef-8ba1-5761756d4a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-12-2&quot;)/span[@class=&quot;text&quot;]</value>
      <webElementGuid>5f12979d-4d35-4baf-8c31-d42ded6ef27c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='bs-select-12-2']/span[2]</value>
      <webElementGuid>f867daf8-5f77-4de7-90a3-d8c2432e49af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select site'])[2]/following::span[4]</value>
      <webElementGuid>7797c4f3-d987-4b6d-a00b-2e5a9bc40e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::span[6]</value>
      <webElementGuid>b321d17b-e807-449d-8f3f-346749bb8e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Global'])[8]/preceding::span[232]</value>
      <webElementGuid>12cf85e3-7d94-46ac-8c2d-616350eb89a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div[2]/ul/li[3]/a/span[2]</value>
      <webElementGuid>90d2894a-4dd8-4c02-a0fd-d1aa037dc867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '012 - PCBA KALLANG, SINGAPORE (012)' or . = '012 - PCBA KALLANG, SINGAPORE (012)')]</value>
      <webElementGuid>d616b518-ff93-4c7f-8ccd-c6e3e1cd9c73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
