<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Comments_Request</name>
   <tag></tag>
   <elementGuidId>0e8ebf47-d5e2-43e2-b9ac-583affdb1221</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#req-comments-text-area</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='req-comments-text-area']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>65bf9215-9ec6-4924-89c4-2bb995c3a8c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>ed8690bd-64d4-4045-8a4e-aa92918ab26e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>comments</value>
      <webElementGuid>48b76782-c43c-47ad-846b-21d678e84479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>af1351ce-9da1-4002-aeec-3f0a0517a148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>req-comments-text-area</value>
      <webElementGuid>1225fb01-cca5-425e-b898-1de21b89679c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>256c7c8a-5880-40a1-be10-93c496e95065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;req-comments-text-area&quot;)</value>
      <webElementGuid>68e856ab-963b-4ee5-820c-c76b40bb9057</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='req-comments-text-area']</value>
      <webElementGuid>e333326e-134f-4823-81e9-e6936b10d28d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='req-project-form']/div[7]/div/textarea</value>
      <webElementGuid>21667a83-dc4d-42e8-a297-f631902f4a18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>ea914a50-9745-4614-9181-714143ec29e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'comments' and @id = 'req-comments-text-area']</value>
      <webElementGuid>1449a63a-84fc-474e-978d-027f17ff1b7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
