<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Commodity code</name>
   <tag></tag>
   <elementGuidId>e4eb61dd-cee8-42bf-8440-d2e98ecb84e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='review-table_wrapper']/div[2]/div/div/div[3]/div[2]/div/table/tbody/tr[15]/td/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>table.gbs-alt-review-table.compact.stripe.hover.af.dataTable.no-footer.DTFC_Cloned > tbody > tr.attribute-row.odd > td.attr-legend.padding > div.splitted-attr-col > div.splitted-attr-col-left-half > div.ihs-attr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>af49d070-96c6-4b45-92ad-170d5d97bb0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ihs-attr</value>
      <webElementGuid>142b9e8b-9754-40f5-b7cb-d3a84c261eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Commodity code</value>
      <webElementGuid>11bce024-751f-4c58-ac2e-7f5834dd3982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;review-table_wrapper&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;DTFC_ScrollWrapper&quot;]/div[@class=&quot;DTFC_LeftWrapper&quot;]/div[@class=&quot;DTFC_LeftBodyWrapper&quot;]/div[@class=&quot;DTFC_LeftBodyLiner&quot;]/table[@class=&quot;gbs-alt-review-table compact stripe hover af dataTable no-footer DTFC_Cloned&quot;]/tbody[1]/tr[@class=&quot;attribute-row odd&quot;]/td[@class=&quot;attr-legend padding&quot;]/div[@class=&quot;splitted-attr-col&quot;]/div[@class=&quot;splitted-attr-col-left-half&quot;]/div[@class=&quot;ihs-attr&quot;]</value>
      <webElementGuid>f136965d-0dbe-4847-8f17-e92eeb0f78f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='review-table_wrapper']/div[2]/div/div/div[3]/div[2]/div/table/tbody/tr[15]/td/div/div/div</value>
      <webElementGuid>39d37826-ce4b-4f6f-8716-2b2ceda488df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FFF Attribute Name'])[2]/following::div[3]</value>
      <webElementGuid>77766ef1-0b8f-4a14-9258-23b55f471c96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Commodity Prefix'])[2]/preceding::div[1]</value>
      <webElementGuid>ddf21f23-5f72-4de6-980b-7283561bbfef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dielectric Material'])[3]/preceding::div[3]</value>
      <webElementGuid>6628d67e-27d0-4988-9a6f-63ec698a94f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/table/tbody/tr[15]/td/div/div/div</value>
      <webElementGuid>e50dcb29-6ab8-40e7-a89f-c0615f9272f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
