<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ceramic Capacitor</name>
   <tag></tag>
   <elementGuidId>f3c9a911-ee66-47dc-a9f1-8120216387a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bs-select-34-19']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bs-select-34-19 > span.text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0cb6e6e8-4a93-4bbb-a265-cbe9ba82d40b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>17f63240-03af-4b1f-9a7e-b8280ae5c85b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ceramic Capacitor</value>
      <webElementGuid>5c06f60e-f3d4-47c0-8bdb-7e0f5375440d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-34-19&quot;)/span[@class=&quot;text&quot;]</value>
      <webElementGuid>f0cfdf92-1041-45f7-8a35-552eadc49c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9aa07d5a-edc1-4ed7-98c9-792b385d3584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>18a40f15-f80a-442a-ad83-42594625f657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ceramic Capacitor</value>
      <webElementGuid>2589c7ba-55b8-45ef-93c3-d6344c28d0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-34-19&quot;)/span[@class=&quot;text&quot;]</value>
      <webElementGuid>ae633108-16dc-4351-85a4-231a70d4422c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='bs-select-34-19']/span[2]</value>
      <webElementGuid>200eeb47-51cb-4e37-b985-541c251d62d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select product category'])[1]/following::span[2]</value>
      <webElementGuid>df1c9b8c-fc9a-41ce-8231-d4c6a16e2abb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parts Review'])[1]/following::span[3]</value>
      <webElementGuid>d38d1bdd-ed0e-4f7b-9c4b-4f846476c977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='With FFF Attributes'])[2]/preceding::span[2]</value>
      <webElementGuid>28394f1b-281e-49cd-8114-153f395c4658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a/span[2]</value>
      <webElementGuid>714fdece-96fc-4fa0-9c58-c5bbfa33e950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Ceramic Capacitor' or . = 'Ceramic Capacitor')]</value>
      <webElementGuid>1175a48f-a023-4c92-866e-eb88ed5bc967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standoff and spacer'])[2]/preceding::span[2]</value>
      <webElementGuid>fba3bc94-a917-4434-b987-0c63f736daab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
