<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Collect It Right</name>
   <tag></tag>
   <elementGuidId>002e3ea3-60aa-4ae3-a24e-7ad5af5590f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cir-home-page']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cir-home-page > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>04cf43c9-469d-44d5-9c94-4a94c3116ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Collect It Right</value>
      <webElementGuid>53492dea-4f97-4949-a46d-65c4765dd8a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cir-home-page&quot;)/span[1]</value>
      <webElementGuid>e184847a-7385-4453-a69d-631007b54016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f8af50f7-86bd-42e5-82b1-b20e16631f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Collect It Right</value>
      <webElementGuid>4ab1701f-0ff2-4955-bf5e-7f51e9db9e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cir-home-page&quot;)/span[1]</value>
      <webElementGuid>440ba0ae-92bd-47ec-aa8b-94e552f9d205</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='cir-home-page']/span</value>
      <webElementGuid>4bbc74db-0d4f-4a88-bf1d-1e1e454cf18e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CIR'])[1]/following::span[1]</value>
      <webElementGuid>d1ed2e44-8123-475e-acf5-32c7fb58d00a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Design for Supply Chain'])[1]/following::span[2]</value>
      <webElementGuid>06974826-7283-4f11-a444-49e8d7aec4ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DWA Dashboards'])[1]/preceding::span[1]</value>
      <webElementGuid>21a5e124-17ed-4ef8-b7ea-df59ceaf84ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TIR'])[1]/preceding::span[2]</value>
      <webElementGuid>f035df10-a070-466f-9116-4af2c4cb72b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Collect It Right']/parent::*</value>
      <webElementGuid>3d7f49b2-b4a3-493f-bba1-3eb10398f0c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li/a/span</value>
      <webElementGuid>16652101-a90e-4fa6-bccb-0c41cc426303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Collect It Right' or . = 'Collect It Right')]</value>
      <webElementGuid>16d719d0-86ec-4110-bcf0-346c44cd51f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
