<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AML Alignment_Menu</name>
   <tag></tag>
   <elementGuidId>6d454aba-fa0e-4c4e-9707-2ad72bce2457</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cir-aml-align-tab']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cir-aml-align-tab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5f1132e7-5724-4b25-bd35-e87bc696e1c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#cir-aml-align</value>
      <webElementGuid>298671a7-cf7d-4202-b826-366acc9b566a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>cir-aml-align</value>
      <webElementGuid>f1291ac3-37c3-4175-8f90-9182730bdd2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>db9916ab-a5da-4217-b156-283746ad1825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>94de5083-98fd-466a-8277-b17ef8b4889d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cir-aml-align-tab</value>
      <webElementGuid>75735c61-ca8c-4f01-81f6-f8626a0833cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>705ac7f7-6b65-429c-ba98-f2ec05b79192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				AML Alignment
			</value>
      <webElementGuid>08c0c715-d24f-4350-b23f-cd98904ac01a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cir-aml-align-tab&quot;)</value>
      <webElementGuid>975dd78e-ca77-471d-8c83-0e84bc8a96c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9eab26de-cdfc-4251-9af2-f9a9605bfa59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#cir-aml-align</value>
      <webElementGuid>0e62b692-e115-451f-912d-765d48db89f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>cir-aml-align</value>
      <webElementGuid>155f3bdc-70e7-429c-bdac-6a1b99c32599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>0cb6ea30-91cf-470c-a052-7546ee7d7a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>c99a6ced-9b06-4055-b030-1b55b5e1c24d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cir-aml-align-tab</value>
      <webElementGuid>296ce564-1439-47da-8c76-68d72fd73877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>e73008c6-5e50-4132-b985-f20861cbf85a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				AML Alignment
			</value>
      <webElementGuid>e29854c9-a88b-4192-9c53-6b21fb469776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cir-aml-align-tab&quot;)</value>
      <webElementGuid>ff82cef8-a850-411d-9ca8-1100413a0662</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cir-aml-align-tab']</value>
      <webElementGuid>d6cee4f7-46f4-41f7-a66b-ee52024442d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cir-menu-panel']/ul/li[8]/div/a[6]</value>
      <webElementGuid>8f77e571-f134-40ce-96ca-c8301bde84bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'AML Alignment')]</value>
      <webElementGuid>c9f8d9ef-84f4-4cb2-8e69-172703dbb117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sourcing Manager'])[1]/following::a[1]</value>
      <webElementGuid>6c9b30fe-a0ba-494a-bee7-80c0acd12d41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customers'])[1]/following::a[2]</value>
      <webElementGuid>719249c6-e350-46c7-aa71-7b6e702a9cd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project ID'])[1]/preceding::a[4]</value>
      <webElementGuid>6fdda9b0-5747-4c0e-aa5e-b86a22945001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project Name'])[1]/preceding::a[4]</value>
      <webElementGuid>4abcc76e-915a-40ee-8ddd-0f237a6abc9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AML Alignment']/parent::*</value>
      <webElementGuid>885112f1-4aaa-433d-a2da-744fbb1031aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#cir-aml-align')]</value>
      <webElementGuid>b2e39ad7-2baa-43ea-bf23-a7f3dea130eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/div/a[6]</value>
      <webElementGuid>7b48bd70-563e-426f-840a-d3bf07284a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#cir-aml-align' and @id = 'cir-aml-align-tab' and (text() = '
				AML Alignment
			' or . = '
				AML Alignment
			')]</value>
      <webElementGuid>878ce8b6-77cc-415f-8b7d-6a85ae830e58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
