<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Logout</name>
   <tag></tag>
   <elementGuidId>bb11f12a-cfc2-454d-ade3-7084c667cd78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='user-menu']/div/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.dropdown-item.tr-link.logout-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>df5a665d-bea7-495e-87c3-a3133b36cc9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item tr-link logout-link</value>
      <webElementGuid>06215bc3-a730-47c8-b29e-802faf009454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>7dbaefa6-7b09-4d3f-894f-7098e9071a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>c01642b2-a585-4068-9b06-69e897c0a900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
							 Logout
						</value>
      <webElementGuid>2fd5404d-496c-417a-b8f7-db159b4d70f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-menu&quot;)/div[@class=&quot;dropdown-menu dropdown-menu-right user-info-holder show&quot;]/a[@class=&quot;dropdown-item tr-link logout-link&quot;]</value>
      <webElementGuid>baeca5a8-7ab0-4eba-a5fa-09b678dde507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>627c9acd-627e-40f5-922c-8e3b81fb4bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item tr-link logout-link</value>
      <webElementGuid>6d8b09c2-0720-4ade-9078-fc6a1670b2de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>5c6e3347-77af-4eb2-99bd-293d68e239a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>90ff9abd-a2b7-4059-9b5e-b3ce8d5eaaf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
							 Logout
						</value>
      <webElementGuid>b9c63880-1252-4ee1-99c1-5cfc57d79404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-menu&quot;)/div[@class=&quot;dropdown-menu dropdown-menu-right user-info-holder show&quot;]/a[@class=&quot;dropdown-item tr-link logout-link&quot;]</value>
      <webElementGuid>f43a2904-530d-43c2-be14-7b48c8e37a19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='user-menu']/div/a[2]</value>
      <webElementGuid>c8c4bbe1-6d8f-44f7-bfe6-f877f5fdd190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chennai, IN Chennai GBS B3'])[1]/following::a[2]</value>
      <webElementGuid>f9fc577f-7329-4081-9afe-7fefa7d087e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='There are no alerts'])[1]/preceding::a[2]</value>
      <webElementGuid>cbd1fb42-8af6-40f3-a103-c1b939e27897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='It-Right Platform'])[1]/preceding::a[2]</value>
      <webElementGuid>cfbfaea1-d3ab-4d00-8fb7-3c25493c458e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>bae8edda-4ca6-4ae2-8bc8-b7295c43dfc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0);')]</value>
      <webElementGuid>2d92a3c1-b310-4620-a519-217a1fb0ad4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/a[2]</value>
      <webElementGuid>a4118ca3-ad92-41fa-894c-aa6b9ce1b676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Logout' and @href = 'javascript:void(0);' and (text() = '
							 Logout
						' or . = '
							 Logout
						')]</value>
      <webElementGuid>38b32c9f-1542-4a65-b27c-0cd692b2b1fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
