<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Commodity</name>
   <tag></tag>
   <elementGuidId>bf099d04-04ea-450d-aebf-843d30007220</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cir-market-intelligence']/div/div/div/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col > div.tabulator > div.tabulator-header > div.tabulator-headers > div.tabulator-col > div.tabulator-col-content > div.tabulator-col-title-holder > div.tabulator-col-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0f5f200f-e316-435d-a664-809cf471af07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tabulator-col-title</value>
      <webElementGuid>b710b987-1967-4f24-9b2e-d93e3b7fa9a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Commodity</value>
      <webElementGuid>6d1bc4cd-9316-4ae3-9cb0-f853b077eb43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cir-market-intelligence&quot;)/div[@class=&quot;col&quot;]/div[@class=&quot;tabulator&quot;]/div[@class=&quot;tabulator-header&quot;]/div[@class=&quot;tabulator-headers&quot;]/div[@class=&quot;tabulator-col&quot;]/div[@class=&quot;tabulator-col-content&quot;]/div[@class=&quot;tabulator-col-title-holder&quot;]/div[@class=&quot;tabulator-col-title&quot;]</value>
      <webElementGuid>489871c3-4889-4a2f-bb80-dc2bc285c396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5c61339f-803a-48ec-b5f2-2728fc80dea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tabulator-col-title</value>
      <webElementGuid>fc0bad5c-ba9a-4bb8-9b26-813d71c8935f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Commodity</value>
      <webElementGuid>815d6674-98f3-409d-92f1-48933017f85c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cir-market-intelligence&quot;)/div[@class=&quot;col&quot;]/div[@class=&quot;tabulator&quot;]/div[@class=&quot;tabulator-header&quot;]/div[@class=&quot;tabulator-headers&quot;]/div[@class=&quot;tabulator-col&quot;]/div[@class=&quot;tabulator-col-content&quot;]/div[@class=&quot;tabulator-col-title-holder&quot;]/div[@class=&quot;tabulator-col-title&quot;]</value>
      <webElementGuid>aaf40562-0362-4a3a-bde1-aa40604338c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cir-market-intelligence']/div/div/div/div/div/div/div/div</value>
      <webElementGuid>4b70a749-910d-48b9-9018-35e4c4249930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[11]/following::div[9]</value>
      <webElementGuid>6d297ceb-9e09-432b-8b46-3de946adb6e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[14]/following::div[9]</value>
      <webElementGuid>e9148fb8-d5e5-4665-9758-7fa85c1a1f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VP Level'])[1]/preceding::div[4]</value>
      <webElementGuid>2905ff74-a7e1-4160-8cdb-860e59e0f65f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GCM Owner'])[1]/preceding::div[10]</value>
      <webElementGuid>18580077-d70f-4e28-8aa4-dcf8546baa12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Commodity']/parent::*</value>
      <webElementGuid>269b8c60-9921-4cff-9ad4-3020e0eeaf2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/div/div/div/div/div</value>
      <webElementGuid>164b585a-e8a9-4a01-8c5d-b1d4a9075cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Commodity' or . = 'Commodity')]</value>
      <webElementGuid>e068e00e-27a0-4901-9257-007d2ad2b66d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
