<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_GBS Project Request</name>
   <tag></tag>
   <elementGuidId>21b4b7a5-7f37-4011-8aee-cb2e94a22c6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='sidebar']/div[2]/ul/li[5]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li[title=&quot;GBS Project Request&quot;] > a.nav-link > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ee7b4dad-206d-4ea2-ae36-fc2d2c99a513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GBS Project Request</value>
      <webElementGuid>a2bf378f-cbd9-43ae-9de1-173bec417e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar&quot;)/div[@class=&quot;group-nav&quot;]/ul[@class=&quot;nav flex-column nav-items&quot;]/li[5]/a[@class=&quot;nav-link&quot;]/span[1]</value>
      <webElementGuid>9acaba25-4df9-479b-8043-7340ce247f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b527412e-758e-407d-a008-9e46765a5180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GBS Project Request</value>
      <webElementGuid>52058f8a-487a-4aae-bb76-85a83aa0d641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar&quot;)/div[@class=&quot;group-nav&quot;]/ul[@class=&quot;nav flex-column nav-items&quot;]/li[5]/a[@class=&quot;nav-link&quot;]/span[1]</value>
      <webElementGuid>95ffbd42-544a-44a5-a26d-128778e319ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c3ab2c8d-af9b-4ed1-afd5-0b0f690c41d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GBS Project Request</value>
      <webElementGuid>c6d167cc-28a3-4d4a-ac99-28fc4e2dcaea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar&quot;)/div[@class=&quot;group-nav&quot;]/ul[@class=&quot;nav flex-column nav-items&quot;]/li[5]/a[@class=&quot;nav-link&quot;]/span[1]</value>
      <webElementGuid>579bc482-f911-4631-bd2a-7c29cdc680f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>29b0944e-bf05-4d91-aa04-3f7e48f6a1a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GBS Project Request</value>
      <webElementGuid>1200827e-eac1-4a37-8e47-0da89466a712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar&quot;)/div[@class=&quot;group-nav&quot;]/ul[@class=&quot;nav flex-column nav-items&quot;]/li[5]/a[@class=&quot;nav-link&quot;]/span[1]</value>
      <webElementGuid>8cd993ce-61a5-4dea-a9f9-286eab32852b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0ff8d259-87c9-4723-b3d6-6fb6d579b605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GBS Project Request</value>
      <webElementGuid>0c8eb8f0-0fe2-4876-aed0-532e67f814d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar&quot;)/div[@class=&quot;group-nav&quot;]/ul[@class=&quot;nav flex-column nav-items&quot;]/li[5]/a[@class=&quot;nav-link&quot;]/span[1]</value>
      <webElementGuid>a180f54b-379c-40ec-83c0-f6d4ae517736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>76cc5867-d628-4523-9f7f-2183c35d9441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GBS Project Request</value>
      <webElementGuid>78bd46d4-3366-4312-9448-da33aebeb5b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar&quot;)/div[@class=&quot;group-nav&quot;]/ul[@class=&quot;nav flex-column nav-items&quot;]/li[5]/a[@class=&quot;nav-link&quot;]/span[1]</value>
      <webElementGuid>5e1bb6e1-df6c-4cb5-962e-7fc04c70c60c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9db41b23-d05c-47b3-9ca2-62069d68ffb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GBS Project Request</value>
      <webElementGuid>610a3bca-09d6-45b0-bf58-1a907f7ca36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar&quot;)/div[@class=&quot;group-nav&quot;]/ul[@class=&quot;nav flex-column nav-items&quot;]/li[5]/a[@class=&quot;nav-link&quot;]/span[1]</value>
      <webElementGuid>40fed8a5-57bb-4580-bc85-0eef60dbf4f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>95c3d4a0-346a-4360-8934-3edb92917f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GBS Project Request</value>
      <webElementGuid>f1fbc2b4-e005-48f1-9d72-c02a60a69339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar&quot;)/div[@class=&quot;group-nav&quot;]/ul[@class=&quot;nav flex-column nav-items&quot;]/li[5]/a[@class=&quot;nav-link&quot;]/span[1]</value>
      <webElementGuid>86bc677b-d14a-4352-a4e7-3511bc8b574f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='sidebar']/div[2]/ul/li[5]/a/span</value>
      <webElementGuid>ded97519-bfd7-4544-877c-ad2d35fbb15f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GBS'])[2]/following::span[1]</value>
      <webElementGuid>de4d27e7-1e17-4859-88c9-d90bc67d94c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supplier Finder'])[1]/following::span[2]</value>
      <webElementGuid>31c54a6b-3da9-4525-94bf-fd874aad12a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Design for Supply Chain'])[1]/preceding::span[1]</value>
      <webElementGuid>7698e572-4797-4e3a-ad4b-5244cd620260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CIR'])[1]/preceding::span[2]</value>
      <webElementGuid>ab0af9ef-f1c6-42e7-ab98-f71ce1a3cc9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='GBS Project Request']/parent::*</value>
      <webElementGuid>8ede87d8-f320-4a2a-85ef-b16f058cb7da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[5]/a/span</value>
      <webElementGuid>ee2b6e11-3831-448e-a65a-a8d6e1e05a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'GBS Project Request' or . = 'GBS Project Request')]</value>
      <webElementGuid>b8eec065-c1c1-47d6-94d9-9694dfa19404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='sidebar']/ul/li[10]/a/span</value>
      <webElementGuid>b69b5fb3-7768-44a0-a9a2-3f0cdbb3da79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GBS'])[1]/following::span[1]</value>
      <webElementGuid>7c7a39ce-e2ea-461a-99a1-c8c2eb04d27b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collect It Right'])[1]/preceding::span[2]</value>
      <webElementGuid>92e0c9a7-beac-43fe-9b74-654398ecb06a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/a/span</value>
      <webElementGuid>1fcc50d6-12ba-424d-8631-6ba9e46ef1aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
