<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_3M COMPANY</name>
   <tag></tag>
   <elementGuidId>c4489a5a-2c8a-424c-bc04-71b0f796cc6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bs-select-13-3']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bs-select-13-3 > span.text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6bf1509c-1800-4a03-bde2-6af42f5c0b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b8252b20-a5ff-45a8-a4bf-65dc08f78ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3M COMPANY</value>
      <webElementGuid>ad561400-ea17-4fbc-8dab-9b247f94b047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-13-3&quot;)/span[@class=&quot;text&quot;]</value>
      <webElementGuid>ab82dd4d-e424-49f6-bf43-612e12a9f7e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dbbff7f1-3773-46fb-8770-42ddcbe30d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>854bab0c-68a2-489f-8e90-e63da6a004f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3M COMPANY</value>
      <webElementGuid>44cd9678-9202-4f20-9438-5d11a6692026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-13-3&quot;)/span[@class=&quot;text&quot;]</value>
      <webElementGuid>fddb35bb-9d42-49b5-ae0e-a7921854d67b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='bs-select-13-3']/span[2]</value>
      <webElementGuid>f40fe27a-c921-4642-9934-cbb08ae7a2ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='None'])[7]/following::span[6]</value>
      <webElementGuid>4c26436d-a6e1-4062-8741-6dff49e35b56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='None'])[6]/following::span[8]</value>
      <webElementGuid>9b97edbb-8807-465c-98ab-20f92d9059bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A SCHULMAN'])[8]/preceding::span[6]</value>
      <webElementGuid>080c6575-4fb6-4e2d-8e5f-180e6f99fde5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A123 SYSTEMS'])[36]/preceding::span[8]</value>
      <webElementGuid>043440b8-1199-4de6-bd22-b8337c1e5421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/div/div[2]/ul/li[4]/a/span[2]</value>
      <webElementGuid>2c3c306f-e09e-430f-843c-6b8b2d34a4ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '3M COMPANY' or . = '3M COMPANY')]</value>
      <webElementGuid>a3d5ba05-6c9d-4f43-b854-4d7ff0478616</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
