<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Logout</name>
   <tag></tag>
   <elementGuidId>d8108e6a-ff9b-40f0-b1a0-7933c4730eab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='user-menu']/div/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.dropdown-item.tr-link.logout-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>01a520a9-ef76-4190-94ea-e50b6d092129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item tr-link logout-link</value>
      <webElementGuid>62200c2b-4057-4df6-984b-e074b0852b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>4c206aca-cae1-483d-af48-e474a6bdfa1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>d7f788a8-a7f9-4475-9416-001552acf1f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
							 Logout
						</value>
      <webElementGuid>7d4ca857-a4fe-41d5-b2c8-0c2c19379a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-menu&quot;)/div[@class=&quot;dropdown-menu dropdown-menu-right user-info-holder show&quot;]/a[@class=&quot;dropdown-item tr-link logout-link&quot;]</value>
      <webElementGuid>b35fb3bd-f9dd-4550-98aa-44f8ce3303ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>84a04ad7-b51b-4ec8-9bf8-ca312b7abd48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item tr-link logout-link</value>
      <webElementGuid>36c74470-9637-4087-b122-dee54e50a90f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>41819066-562c-4f94-aa29-45542764316d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>4b55d658-9da1-4a1e-99cb-4bcae1ad56ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
							 Logout
						</value>
      <webElementGuid>54012253-0d07-4e16-9b72-60d8630f1c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-menu&quot;)/div[@class=&quot;dropdown-menu dropdown-menu-right user-info-holder show&quot;]/a[@class=&quot;dropdown-item tr-link logout-link&quot;]</value>
      <webElementGuid>08d67ccd-cbf0-4f17-a006-9ba7657fd4a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>136234eb-2416-41a2-9a14-7dff176f8058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item tr-link logout-link</value>
      <webElementGuid>34573c5a-8f9c-440a-948a-fd92cfaf364e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>e67a6776-3beb-4d52-96c9-c6016bfd45a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>2e40ee59-1d22-46a5-9ba1-dd47708a395f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
							 Logout
						</value>
      <webElementGuid>9f42ad13-8b9c-4469-849b-aee3be66cd85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-menu&quot;)/div[@class=&quot;dropdown-menu dropdown-menu-right user-info-holder show&quot;]/a[@class=&quot;dropdown-item tr-link logout-link&quot;]</value>
      <webElementGuid>18693b23-028d-45ad-8a59-6c68beb33076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c90a5954-f9c7-46d2-9250-e88c2ef99c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item tr-link logout-link</value>
      <webElementGuid>e20b18f6-e930-43d9-b208-88be41a98f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>7a2d2b15-02c2-44fd-8301-82c844b75dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>20c10327-8cf8-42b1-9dce-0c486cf9b3b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
							 Logout
						</value>
      <webElementGuid>9fc35b37-4542-4401-a1eb-ac9980a9590c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-menu&quot;)/div[@class=&quot;dropdown-menu dropdown-menu-right user-info-holder show&quot;]/a[@class=&quot;dropdown-item tr-link logout-link&quot;]</value>
      <webElementGuid>1c2f95d0-1fdb-4791-90e4-d05126150d00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='user-menu']/div/a[2]</value>
      <webElementGuid>165969c1-5acf-475d-affb-d729bdc94425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chennai, IN Chennai GBS B3'])[1]/following::a[2]</value>
      <webElementGuid>4d4a9b53-e83e-4d8c-b8aa-2eff4cf6c8ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='There are no alerts'])[1]/preceding::a[2]</value>
      <webElementGuid>a208c5a9-2cb3-45fe-85ec-06401a325000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='It-Right Platform'])[1]/preceding::a[2]</value>
      <webElementGuid>0d641210-ed8e-416d-ace9-3c46b444a8a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>bd126d04-fd7e-4690-a855-1f0b1ef800e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0);')]</value>
      <webElementGuid>26ee7e80-b93a-43bd-9333-465087fac66f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/a[2]</value>
      <webElementGuid>cbd09211-3094-4e16-a381-55bbf01e9b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Logout' and @href = 'javascript:void(0);' and (text() = '
							 Logout
						' or . = '
							 Logout
						')]</value>
      <webElementGuid>aa59a579-5691-4948-bb16-f0b29e2ffefd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
