<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_datatable_header</name>
   <tag></tag>
   <elementGuidId>1381028d-fafc-4eaa-9c91-c9c79828b669</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='supplier-data_wrapper']/div[2]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.dataTables_scrollHead</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>afe62ca4-4508-4c0a-bb74-41efb8c2c5f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dataTables_scrollHead</value>
      <webElementGuid>954f0b68-5339-4179-b0ec-5d93026e3ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Global Supp CodeSupplierSupplier TypePreferredVP GroupCommodity GroupRegionSegmentLevel 1 DescLevel 2 DescLevel 3 DescGCM NameDPL Ranking</value>
      <webElementGuid>1bace920-1c19-4bd0-805e-a62bb2ca8a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;supplier-data_wrapper&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;dataTables_scroll&quot;]/div[@class=&quot;dataTables_scrollHead&quot;]</value>
      <webElementGuid>ef18d9e3-de12-4c22-9b6a-54239eab56b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4bbcf1c4-cfd5-403d-a839-92c478df8078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dataTables_scrollHead</value>
      <webElementGuid>33b6e524-3f54-43b1-aa0a-13e877b7ca51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Global Supp CodeSupplierSupplier TypePreferredVP GroupCommodity GroupRegionSegmentLevel 1 DescLevel 2 DescLevel 3 DescGCM NameDPL Ranking</value>
      <webElementGuid>acff7aac-13a5-4bfb-a878-7419c67cbc86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;supplier-data_wrapper&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;dataTables_scroll&quot;]/div[@class=&quot;dataTables_scrollHead&quot;]</value>
      <webElementGuid>89f67545-02f7-4b0c-9dbb-e5acef456ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c2afdf84-3ea8-4c87-91ea-2fae776b6d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dataTables_scrollHead</value>
      <webElementGuid>40f33585-c1ef-4ce5-876b-9f3a17d237f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Global Supp CodeSupplierSupplier TypePreferredVP GroupCommodity GroupRegionSegmentLevel 1 DescLevel 2 DescLevel 3 DescGCM NameDPL Ranking</value>
      <webElementGuid>8e62bb61-194b-41c9-9f48-a7fdc4c99937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;supplier-data_wrapper&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;dataTables_scroll&quot;]/div[@class=&quot;dataTables_scrollHead&quot;]</value>
      <webElementGuid>c8e0e4ca-e376-4988-be96-7fcb44b29251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7a778514-ad9a-4747-914c-d30678a7dddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dataTables_scrollHead</value>
      <webElementGuid>f7af0a2f-a07c-4544-904e-6ef3af2ff136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Global Supp CodeSupplierSupplier TypePreferredVP GroupCommodity GroupRegionSegmentLevel 1 DescLevel 2 DescLevel 3 DescGCM NameDPL Ranking</value>
      <webElementGuid>837686e3-75e0-4e8b-9480-d2e8e4294395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;supplier-data_wrapper&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;dataTables_scroll&quot;]/div[@class=&quot;dataTables_scrollHead&quot;]</value>
      <webElementGuid>b969a392-4ba3-4d77-a6ee-72c7c790d92a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='supplier-data_wrapper']/div[2]/div/div/div</value>
      <webElementGuid>79194934-d551-40b0-aeee-f21b70942df4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search:'])[1]/following::div[4]</value>
      <webElementGuid>5f563e2d-8243-4596-8372-12e60a9dad17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div</value>
      <webElementGuid>0a1114e0-138e-4a5e-a286-a2d30de7e706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Global Supp CodeSupplierSupplier TypePreferredVP GroupCommodity GroupRegionSegmentLevel 1 DescLevel 2 DescLevel 3 DescGCM NameDPL Ranking' or . = 'Global Supp CodeSupplierSupplier TypePreferredVP GroupCommodity GroupRegionSegmentLevel 1 DescLevel 2 DescLevel 3 DescGCM NameDPL Ranking')]</value>
      <webElementGuid>d8d2d1c8-140f-41ca-a992-84b9ea951de6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
