<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_VPGroupDropdown</name>
   <tag></tag>
   <elementGuidId>77bca947-461e-4c70-a5f6-29c5f815a8c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='vp-group']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vp-group</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a3f275ff-8997-439a-b271-acab4d3067ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vp-group</value>
      <webElementGuid>04b7972c-fa17-42ee-8dc2-2507096955e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control selectpicker</value>
      <webElementGuid>c2447fca-8896-4b09-a559-29a20eec1ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actions-box</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e6d9eeb9-b3e2-45dc-ab6f-3ce55cd85723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-selected-text-format</name>
      <type>Main</type>
      <value>count</value>
      <webElementGuid>75cab9c9-10ca-4488-a14f-4b4393cff860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-style-base</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>61568fce-8095-4389-a40f-1deae9ed1903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>COMMODITY PRODUCT GROUPINTERCONNECT PRODUCT GROUPMEMORY STORAGE PRODUCT GROUPSEMICONDUCTOR PRODUCT GROUPVP GLOBAL MECHANICALVP REGIONAL MECHANICAL</value>
      <webElementGuid>951994fb-c45e-45b4-a7bb-f7b934eb31b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vp-group&quot;)</value>
      <webElementGuid>7f14c760-c0fe-47be-93b0-e95de4019cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e105bfb3-6fab-4f05-9282-fed0b7a9efe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vp-group</value>
      <webElementGuid>0f4553ba-e539-4883-a319-46975eff8a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control selectpicker</value>
      <webElementGuid>791694b0-b0b5-48d8-ada6-2061bd4a92f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actions-box</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8712db5d-ec1a-4629-bbff-34bb9f26ea4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-selected-text-format</name>
      <type>Main</type>
      <value>count</value>
      <webElementGuid>223609d1-a007-4142-a796-fb7f373c16c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-style-base</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>70ee91f6-3621-41c9-843d-8d407f529d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>COMMODITY PRODUCT GROUPINTERCONNECT PRODUCT GROUPMEMORY STORAGE PRODUCT GROUPSEMICONDUCTOR PRODUCT GROUPVP GLOBAL MECHANICALVP REGIONAL MECHANICAL</value>
      <webElementGuid>5682539a-9b5e-432e-b18c-6b5fbb41f56a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vp-group&quot;)</value>
      <webElementGuid>dbe803a6-8882-4cb1-88ba-e8991ae47077</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='vp-group']</value>
      <webElementGuid>ea35e361-0488-428c-ad66-4a11b5367406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vp-group-box']/div/div/select</value>
      <webElementGuid>a910b28a-77de-4b62-ab01-026569c1794f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VP Group'])[1]/following::select[1]</value>
      <webElementGuid>07bd8c8c-8c0a-4424-a259-dbeb537f62e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SOUTH_ASIA'])[2]/following::select[1]</value>
      <webElementGuid>b6a2c89f-53ba-4bc5-b63a-1271a94b7475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nothing selected'])[2]/preceding::select[1]</value>
      <webElementGuid>a1eb0d6d-0115-4777-abe0-b3757a8cd1a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[2]/preceding::select[1]</value>
      <webElementGuid>ad79c31c-988c-4653-9a68-cef1b24b9d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>728931d1-8e95-4bfb-b94d-51dcf2722f62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'vp-group' and (text() = 'COMMODITY PRODUCT GROUPINTERCONNECT PRODUCT GROUPMEMORY STORAGE PRODUCT GROUPSEMICONDUCTOR PRODUCT GROUPVP GLOBAL MECHANICALVP REGIONAL MECHANICAL' or . = 'COMMODITY PRODUCT GROUPINTERCONNECT PRODUCT GROUPMEMORY STORAGE PRODUCT GROUPSEMICONDUCTOR PRODUCT GROUPVP GLOBAL MECHANICALVP REGIONAL MECHANICAL')]</value>
      <webElementGuid>20b312ce-53ba-4beb-9444-9a14426ed776</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
