<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SupplierTypeDropdown</name>
   <tag></tag>
   <elementGuidId>e969619f-2571-4de6-9fe1-dbbb97d3bc3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='supp-type']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#supp-type</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0499dc4d-3a98-4f6a-9a9c-6cf4450b57ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>supp-type</value>
      <webElementGuid>040c3aeb-c54a-43e8-9df4-f9b532025897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c0a11da5-f843-4baf-ba34-4a0a10c0540f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-style-base</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8cba25c4-5459-4988-92d3-57866ff6fcb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ALLBROKERDISTRIBUTORFLEXTRONICSMANUFACTURER</value>
      <webElementGuid>d0d0de0d-9b6b-4573-9b42-b8b717171f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;supp-type&quot;)</value>
      <webElementGuid>bed131a7-8091-491d-b272-75fe33c655ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d0dc792b-0bc8-40a7-b130-c7fa51de1903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>supp-type</value>
      <webElementGuid>e81dc2a0-3a1f-4c60-90ba-37a516a5ab66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0520f4a6-19f7-4c48-9871-904dde17b627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-style-base</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b2e5d5bc-995b-4726-b1b0-4b21273d9767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ALLBROKERDISTRIBUTORFLEXTRONICSMANUFACTURER</value>
      <webElementGuid>d735d904-fee4-407f-953a-35385d256da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;supp-type&quot;)</value>
      <webElementGuid>3d9ef2c6-f387-463a-b9af-22347ca46742</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='supp-type']</value>
      <webElementGuid>85d24f1d-5735-48b1-8ad0-655419162030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='supp-type-box']/div/div/select</value>
      <webElementGuid>30a90db4-a87b-42df-8244-49404bfbcebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supplier Type'])[1]/following::select[1]</value>
      <webElementGuid>d24d038a-3623-4e1c-9dbb-67fdf73d6750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MEDICAL'])[2]/following::select[1]</value>
      <webElementGuid>374ed779-ede5-41e2-ac9f-4bc545e23552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALL'])[4]/preceding::select[1]</value>
      <webElementGuid>bff4e62f-dc71-4d13-842c-1572cb398b2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALL'])[5]/preceding::select[1]</value>
      <webElementGuid>7706fcd0-355d-445d-a2d2-4d90aa79a1aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/select</value>
      <webElementGuid>19376fd4-a478-4f7c-8f4b-c880d8bba5a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'supp-type' and (text() = 'ALLBROKERDISTRIBUTORFLEXTRONICSMANUFACTURER' or . = 'ALLBROKERDISTRIBUTORFLEXTRONICSMANUFACTURER')]</value>
      <webElementGuid>7a4f5495-f30f-4c38-b01e-41dbc0e88d19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
