<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Level1DescValue</name>
   <tag></tag>
   <elementGuidId>3a08f6a1-0f3b-4e89-a4ee-296938be8cc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='supplier-data']/tbody/tr/td[9]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>ef878b55-7201-4107-865a-47cfff552240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DISTRIBUTOR</value>
      <webElementGuid>90dae245-d072-4acb-8114-b60743207073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;supplier-data&quot;)/tbody[1]/tr[1]/td[9]</value>
      <webElementGuid>ea6683aa-72fa-4279-b366-b24f9c8ce402</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='supplier-data']/tbody/tr/td[9]</value>
      <webElementGuid>fd4d4bb3-1427-4339-9469-53a28024bebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FIS'])[3]/following::td[1]</value>
      <webElementGuid>c1cfd473-629b-41e9-b560-6f01a8cd47ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALL'])[5]/following::td[2]</value>
      <webElementGuid>ac0ea1e2-c189-4292-afdd-05d80d32b2d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DISTRIBUTOR'])[12]/preceding::td[1]</value>
      <webElementGuid>c8cb009d-a240-46f6-8d32-729bdec25acf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ANCA MATEUT'])[1]/preceding::td[3]</value>
      <webElementGuid>b42fb800-09b5-4944-9043-4dac8ae90809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]</value>
      <webElementGuid>db04bdaa-bc51-4272-96e9-4c8cadf4d042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'DISTRIBUTOR' or . = 'DISTRIBUTOR')]</value>
      <webElementGuid>d385a031-ce57-4fba-b7e1-9bb81b432792</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
