<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_SupplierName</name>
   <tag></tag>
   <elementGuidId>34d07280-b761-42c2-80e7-f2466a26e6d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='supplier-data']/tbody/tr/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.sorting_1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;supplier-data&quot;)/tbody[1]/tr[1]/td[@class=&quot;sorting_1&quot;][count(. | //*[(text() = '5D INDUSTRIA' or . = '5D INDUSTRIA')]) = count(//*[(text() = '5D INDUSTRIA' or . = '5D INDUSTRIA')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c75c1d14-d32f-4e6c-ba78-17fb8dfe5d45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sorting_1</value>
      <webElementGuid>659fb5a9-3d0b-487b-b31d-747944b39368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5D INDUSTRIA</value>
      <webElementGuid>21e48240-3e6d-489d-9e9b-6429c96df83e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;supplier-data&quot;)/tbody[1]/tr[1]/td[@class=&quot;sorting_1&quot;]</value>
      <webElementGuid>dd547399-ea6f-4cb8-8e63-11f456587f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>b1b4ff4e-982b-48e4-8bfc-a616180e91be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sorting_1</value>
      <webElementGuid>6e017905-8828-48ee-b9fe-f7cd2e8f13c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5D INDUSTRIA</value>
      <webElementGuid>b3f3f404-8f0d-42fa-b489-fd6c55f75956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;supplier-data&quot;)/tbody[1]/tr[@class=&quot;odd-row&quot;]/td[@class=&quot;sorting_1&quot;]</value>
      <webElementGuid>d186484f-74b7-44e4-800a-ac69a17bae29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>94c40fe3-21b3-42df-a042-6087a6c915cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sorting_1</value>
      <webElementGuid>98461db3-feb3-4837-aa4f-2288c956ce61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5D INDUSTRIA</value>
      <webElementGuid>650b2717-abb5-439f-a29b-3e4bb0e6ec8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;supplier-data&quot;)/tbody[1]/tr[1]/td[@class=&quot;sorting_1&quot;]</value>
      <webElementGuid>5d91135e-d629-4934-8721-629cfbeb75b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>9bad36b4-a9e0-4917-af6a-a49e0536ffb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sorting_1</value>
      <webElementGuid>ba7a2710-1477-4322-919f-62bbeb564e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5D INDUSTRIA</value>
      <webElementGuid>69c7e698-8738-452d-b402-4550834b536f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;supplier-data&quot;)/tbody[1]/tr[@class=&quot;odd-row&quot;]/td[@class=&quot;sorting_1&quot;]</value>
      <webElementGuid>35dbd0ce-59f9-436f-b8a3-a9ae293057a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='supplier-data']/tbody/tr/td[2]</value>
      <webElementGuid>cb9d8fd0-ddd4-40bb-991a-627a807e5fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S03171'])[1]/following::td[1]</value>
      <webElementGuid>27e8bb2f-0b50-4740-a979-a67684dfd66a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DPL Ranking'])[2]/following::td[2]</value>
      <webElementGuid>e2219bc8-51b9-45c8-8a71-fe9f1c827f1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MANUFACTURER'])[3]/preceding::td[1]</value>
      <webElementGuid>5eb8e219-2499-4a1a-b918-742b77168b04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PREFERRED'])[1]/preceding::td[2]</value>
      <webElementGuid>a5d8f2ec-b528-4bb3-845b-6c9ce3882ca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>9c0f8bad-6206-43fe-98aa-a90198f8fe97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '5D INDUSTRIA' or . = '5D INDUSTRIA')]</value>
      <webElementGuid>d522067e-0128-4b3a-9dd7-d3d2a4b243e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
