<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_SupplierTypeValue</name>
   <tag></tag>
   <elementGuidId>aa0fadfe-932f-4038-89fd-931272625958</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='supplier-data']/tbody/tr/td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>ed4f846b-72cb-492e-9839-a554f4b45b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DISTRIBUTOR</value>
      <webElementGuid>5a1deb0b-68be-4a6a-9509-21baccd4d10e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;supplier-data&quot;)/tbody[1]/tr[1]/td[3]</value>
      <webElementGuid>2160e665-72f3-4e0e-9188-b0cf8ea2f1fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='supplier-data']/tbody/tr/td[3]</value>
      <webElementGuid>b3876f91-52af-42fd-b1fa-87f5d9c870eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ARROW ASIA DISTRIBUTION'])[3]/following::td[1]</value>
      <webElementGuid>02ba8818-e225-4039-889f-7a169274699d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S02790'])[1]/following::td[2]</value>
      <webElementGuid>5f523a6e-b0af-4be3-a33b-0d4b5a8b7d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PREFERRED'])[1]/preceding::td[1]</value>
      <webElementGuid>964d48e9-aa08-479d-a18a-74b035d360c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MEMORY STORAGE PRODUCT GROUP'])[4]/preceding::td[2]</value>
      <webElementGuid>d0a5b28f-613b-4733-aedd-93452e1b631c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]</value>
      <webElementGuid>9310010c-0976-4bd2-816a-75353fe181e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'DISTRIBUTOR' or . = 'DISTRIBUTOR')]</value>
      <webElementGuid>f21fd0ac-7499-4cf7-b4d4-671dc9240ebc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
