<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Project file-excel</name>
   <tag></tag>
   <elementGuidId>d7da79db-9093-4746-ac03-100a0888bbdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='50965']/td[17]/div/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.far.fa-file-excel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>baa6982d-491f-44de-bb76-1049d01ce234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>far fa-file-excel</value>
      <webElementGuid>fbb48f26-4579-4207-8a86-0596f31ac222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f82c6aad-c99f-44ac-8dd8-9bce9e90c430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;50965&quot;)/td[@class=&quot;dt-body-center action-links&quot;]/div[@class=&quot;btn-group export-dropdown&quot;]/a[@class=&quot;dropdown-toggle&quot;]/i[@class=&quot;far fa-file-excel&quot;]</value>
      <webElementGuid>51a68a64-ea86-4c02-b58d-f9e41d4c4fee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='50965']/td[17]/div/a/i</value>
      <webElementGuid>469a657b-14fd-491d-9e0e-37f47a0178b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[17]/div/a/i</value>
      <webElementGuid>bd1f0fe6-babd-4523-9051-0fa1e817aad4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
